Resources:
  MyFirstS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
  MySecondS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
Outputs:
  DomainURL:
    Value: !GetAtt MySecondS3Bucket.WebsiteURL